# Importando la paquetería.
https://numpy.org/

In [1]:
import numpy as np

# ¿Cómo buscar ayuda desde la libreta de Jupyter?
- <b>Opción 1</b>: Escribir <b>np</b> luego escribir un punto y por último presionar la tecla "<b>TAB</b>" para mostrar diferentes opciones de autocompletado.
- <b>Opción 2</b>: Buscar la documentación incluida con la función "<b>np?</b>"

In [2]:
#np?

# Creando arreglos de números con Numpy.

### Arreglos llenos de ceros.

In [3]:
arreglo = np.zeros(10, dtype = int)
print(arreglo)

[0 0 0 0 0 0 0 0 0 0]


In [4]:
arreglo = np.zeros(10, dtype = bool)
print(arreglo)

[False False False False False False False False False False]


In [5]:
arreglo = np.zeros(10, dtype = float)
print(arreglo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Arreglos llenos de unos.

In [6]:
arreglo = np.ones(10, dtype = int)
print(arreglo)

[1 1 1 1 1 1 1 1 1 1]


In [7]:
arreglo = np.ones(10, dtype = bool)
print(arreglo)

[ True  True  True  True  True  True  True  True  True  True]


In [8]:
arreglo = np.ones(10, dtype = float)
print(arreglo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Arreglos llenos del mismo valor.

In [9]:
arreglo = np.full(10, 5)
print(arreglo)

[5 5 5 5 5 5 5 5 5 5]


In [10]:
arreglo = np.full(10, "a")
print(arreglo)

['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']


### Arreglos de dos dimensiones.

In [11]:
arreglo = np.full((5, 10), 2)
# Imprimamos el arreglo.
print(arreglo)
print()
# Imprimamos la forma del arreglo.
print(arreglo.shape)
print()
# Imprimamos la cantidad de elementos del arreglo.
print(arreglo.size)

[[2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]]

(5, 10)

50


In [12]:
print(arreglo[0])

[2 2 2 2 2 2 2 2 2 2]


In [13]:
print(arreglo[0][0]) 

2


### Arreglos llenos con valores enteros aleatorios.
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html

In [14]:
# los primeros dos números son el rango y el tercero es cuántos números quieres que genere
arreglo = np.random.randint(5,15,40)
print(arreglo) 

[11  9  8 11  7  6 10  9 13  6 12  6  7 10  5 12  6  8 13 10  9  6  7  9
  9  8 13  7  5 11  7  5  8 11  6  9  8 10  9 12]


### Arreglos llenos con valores aleatorios entre cero y uno.
https://numpy.org/doc/1.16/reference/generated/numpy.random.random.html

In [15]:
# para el caso de decimales solo le indicas la dimensión del arreglo, los números que creará serán entre 0 y 1.
arreglo = np.random.rand(5,3)
print(arreglo)

[[0.33954944 0.17434143 0.30097277]
 [0.21166561 0.09548645 0.75892767]
 [0.08892648 0.44545696 0.06270668]
 [0.15803656 0.20509535 0.6606449 ]
 [0.33872751 0.43518491 0.71921485]]


### Arreglos llenos con valores uniformemente distribuidos.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [16]:
inicio = 0
fin = 5
elementos = 20

In [17]:
x = np.linspace(inicio, fin, elementos)
print(x)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [18]:
print(x[0])
print(x[1])
print(x[19])

0.0
0.2631578947368421
5.0


$Elemento[0] = 0$
<br>$Elemento[1] = Elemento[0] + 0.26315789473684210526315789473684$
<br>$Elemento[2] = Elemento[1] + 0.26315789473684210526315789473684$
<br>$\vdots$
<br>$Elemento[19] = Elemento[18] + 0.26315789473684210526315789473684$

In [19]:
inicio = 5
fin = 8
elementos = 6

### ¿Cómo calculamos la diferencia entre cada punto?
$\Delta = \frac{fin - inicio}{elementos - 1}$
<br>
<br>$\Delta = \frac{8 - 5}{6 - 1}$
<br>
<br>$\Delta = \frac{3}{5}$
<br>
<br>$\Delta = 0.6$

In [20]:
x = np.linspace(inicio, fin, elementos)
print(x)

[5.  5.6 6.2 6.8 7.4 8. ]


# Cambiando la forma de los arreglos.

In [21]:
x = np.linspace(0, 10, 30)
print(x)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]


In [22]:
print(x.shape)

(30,)


In [23]:
x = x.reshape((15,2))
print(x)

[[ 0.          0.34482759]
 [ 0.68965517  1.03448276]
 [ 1.37931034  1.72413793]
 [ 2.06896552  2.4137931 ]
 [ 2.75862069  3.10344828]
 [ 3.44827586  3.79310345]
 [ 4.13793103  4.48275862]
 [ 4.82758621  5.17241379]
 [ 5.51724138  5.86206897]
 [ 6.20689655  6.55172414]
 [ 6.89655172  7.24137931]
 [ 7.5862069   7.93103448]
 [ 8.27586207  8.62068966]
 [ 8.96551724  9.31034483]
 [ 9.65517241 10.        ]]


In [24]:
print(x.shape)

(15, 2)


In [25]:
# el -1 hace que automáticamente calcule las columnas necesarias después de especificarle cuántos renglones quieres.
x = x.reshape((5,-1))
print(x)

[[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793]
 [ 2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345]
 [ 4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897]
 [ 6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448]
 [ 8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]]


In [26]:
print(x.shape)

(5, 6)


In [28]:
x = x.reshape((-1,6))
print(x)

[[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793]
 [ 2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345]
 [ 4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897]
 [ 6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448]
 [ 8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]]


In [29]:
print(x.shape)

(5, 6)


# Haciendo operaciones con arreglos.

In [30]:
x = np.full(5, 10)
y = np.linspace(2, 10, 5)
print(x)
print(y)

[10 10 10 10 10]
[ 2.  4.  6.  8. 10.]


In [31]:
print(x + y)

[12. 14. 16. 18. 20.]


In [32]:
print(x - y)

[8. 6. 4. 2. 0.]


In [33]:
print(x * y)

[ 20.  40.  60.  80. 100.]


In [34]:
print(y**2)

[  4.  16.  36.  64. 100.]


# Algunos operadores disponibles en Numpy
$np.add$
<br>$np.substract$
<br>$np.negative$
<br>$np.multiply$
<br>$np.divide$
<br>$np.power$

In [35]:
print(np.add(x,2))

[12 12 12 12 12]


In [36]:
print(np.power(y,3))

[   8.   64.  216.  512. 1000.]


# Algunas funciones disponibles en Numpy
$np.abs$
<br>$np.sin$
<br>$np.cos$
<br>$np.tan$
<br>$np.exp$
<br>$np.log$

In [37]:
print(np.exp(y))

[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]


In [38]:
print(np.cos(y))

[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153]


# Algunas funciones de estádistica disponibles en Numpy
$np.min$
<br>$np.max$
<br>$np.std$
<br>$np.var$
<br>$np.median$
<br>$np.percentile$

In [39]:
print(np.max(y))

10.0


In [40]:
print(np.std(y))

2.8284271247461903
